/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCallsRouteImport } from './routes/_authenticated/calls'
import { Route as AuthenticatedChatsRouteImport } from './routes/_authenticated/chats'
import { Route as AuthenticatedCommunitiesRouteImport } from './routes/_authenticated/communities'
import { Route as AuthenticatedNewGroupRouteImport } from './routes/_authenticated/new-group'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedUpdatesRouteImport } from './routes/_authenticated/updates'
import { Route as AuthenticatedCallUserIdRouteImport } from './routes/_authenticated/call.$userId'
import { Route as AuthenticatedChatChatIdRouteImport } from './routes/_authenticated/chat.$chatId'
import { Route as AuthenticatedContactChatIdRouteImport } from './routes/_authenticated/contact.$chatId'
import { Route as AuthenticatedGroupChatIdRouteImport } from './routes/_authenticated/group.$chatId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCallsRoute = AuthenticatedCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatsRoute = AuthenticatedChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunitiesRoute =
  AuthenticatedCommunitiesRouteImport.update({
    id: '/communities',
    path: '/communities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNewGroupRoute = AuthenticatedNewGroupRouteImport.update({
  id: '/new-group',
  path: '/new-group',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUpdatesRoute = AuthenticatedUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCallUserIdRoute = AuthenticatedCallUserIdRouteImport.update({
  id: '/call/$userId',
  path: '/call/$userId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatChatIdRoute = AuthenticatedChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactChatIdRoute =
  AuthenticatedContactChatIdRouteImport.update({
    id: '/contact/$chatId',
    path: '/contact/$chatId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGroupChatIdRoute =
  AuthenticatedGroupChatIdRouteImport.update({
    id: '/group/$chatId',
    path: '/group/$chatId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/chats': typeof AuthenticatedChatsRoute
  '/communities': typeof AuthenticatedCommunitiesRoute
  '/new-group': typeof AuthenticatedNewGroupRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/updates': typeof AuthenticatedUpdatesRoute
  '/call/$userId': typeof AuthenticatedCallUserIdRoute
  '/chat/$chatId': typeof AuthenticatedChatChatIdRoute
  '/contact/$chatId': typeof AuthenticatedContactChatIdRoute
  '/group/$chatId': typeof AuthenticatedGroupChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/chats': typeof AuthenticatedChatsRoute
  '/communities': typeof AuthenticatedCommunitiesRoute
  '/new-group': typeof AuthenticatedNewGroupRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/updates': typeof AuthenticatedUpdatesRoute
  '/call/$userId': typeof AuthenticatedCallUserIdRoute
  '/chat/$chatId': typeof AuthenticatedChatChatIdRoute
  '/contact/$chatId': typeof AuthenticatedContactChatIdRoute
  '/group/$chatId': typeof AuthenticatedGroupChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/calls': typeof AuthenticatedCallsRoute
  '/_authenticated/chats': typeof AuthenticatedChatsRoute
  '/_authenticated/communities': typeof AuthenticatedCommunitiesRoute
  '/_authenticated/new-group': typeof AuthenticatedNewGroupRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/updates': typeof AuthenticatedUpdatesRoute
  '/_authenticated/call/$userId': typeof AuthenticatedCallUserIdRoute
  '/_authenticated/chat/$chatId': typeof AuthenticatedChatChatIdRoute
  '/_authenticated/contact/$chatId': typeof AuthenticatedContactChatIdRoute
  '/_authenticated/group/$chatId': typeof AuthenticatedGroupChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calls'
    | '/chats'
    | '/communities'
    | '/new-group'
    | '/profile'
    | '/settings'
    | '/updates'
    | '/call/$userId'
    | '/chat/$chatId'
    | '/contact/$chatId'
    | '/group/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calls'
    | '/chats'
    | '/communities'
    | '/new-group'
    | '/profile'
    | '/settings'
    | '/updates'
    | '/call/$userId'
    | '/chat/$chatId'
    | '/contact/$chatId'
    | '/group/$chatId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/calls'
    | '/_authenticated/chats'
    | '/_authenticated/communities'
    | '/_authenticated/new-group'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/updates'
    | '/_authenticated/call/$userId'
    | '/_authenticated/chat/$chatId'
    | '/_authenticated/contact/$chatId'
    | '/_authenticated/group/$chatId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calls': {
      id: '/_authenticated/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AuthenticatedCallsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats': {
      id: '/_authenticated/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communities': {
      id: '/_authenticated/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof AuthenticatedCommunitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-group': {
      id: '/_authenticated/new-group'
      path: '/new-group'
      fullPath: '/new-group'
      preLoaderRoute: typeof AuthenticatedNewGroupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/updates': {
      id: '/_authenticated/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof AuthenticatedUpdatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/call/$userId': {
      id: '/_authenticated/call/$userId'
      path: '/call/$userId'
      fullPath: '/call/$userId'
      preLoaderRoute: typeof AuthenticatedCallUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$chatId': {
      id: '/_authenticated/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof AuthenticatedChatChatIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contact/$chatId': {
      id: '/_authenticated/contact/$chatId'
      path: '/contact/$chatId'
      fullPath: '/contact/$chatId'
      preLoaderRoute: typeof AuthenticatedContactChatIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/group/$chatId': {
      id: '/_authenticated/group/$chatId'
      path: '/group/$chatId'
      fullPath: '/group/$chatId'
      preLoaderRoute: typeof AuthenticatedGroupChatIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCallsRoute: typeof AuthenticatedCallsRoute
  AuthenticatedChatsRoute: typeof AuthenticatedChatsRoute
  AuthenticatedCommunitiesRoute: typeof AuthenticatedCommunitiesRoute
  AuthenticatedNewGroupRoute: typeof AuthenticatedNewGroupRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUpdatesRoute: typeof AuthenticatedUpdatesRoute
  AuthenticatedCallUserIdRoute: typeof AuthenticatedCallUserIdRoute
  AuthenticatedChatChatIdRoute: typeof AuthenticatedChatChatIdRoute
  AuthenticatedContactChatIdRoute: typeof AuthenticatedContactChatIdRoute
  AuthenticatedGroupChatIdRoute: typeof AuthenticatedGroupChatIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCallsRoute: AuthenticatedCallsRoute,
  AuthenticatedChatsRoute: AuthenticatedChatsRoute,
  AuthenticatedCommunitiesRoute: AuthenticatedCommunitiesRoute,
  AuthenticatedNewGroupRoute: AuthenticatedNewGroupRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUpdatesRoute: AuthenticatedUpdatesRoute,
  AuthenticatedCallUserIdRoute: AuthenticatedCallUserIdRoute,
  AuthenticatedChatChatIdRoute: AuthenticatedChatChatIdRoute,
  AuthenticatedContactChatIdRoute: AuthenticatedContactChatIdRoute,
  AuthenticatedGroupChatIdRoute: AuthenticatedGroupChatIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
